version: "3.9"

services:
  mock-oidc:
    build:
      context: ./mock-oidc
      dockerfile: Dockerfile
    container_name: mock-oidc
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 8081

  claim-for-payment-service:
    build:
      context: ./claim-for-payment-service
      dockerfile: Dockerfile
    container_name: claim-for-payment-service
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 8080
      # Tell BFF to trust the mock OIDC server
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://mock-oidc:8081/mock-issuer
    depends_on:
      - mock-oidc
