-- Enable UUID generation in Postgres (ignored by H2)
CREATE TABLE IF NOT EXISTS submissions (
    id                          UUID PRIMARY KEY,
    friendly_id                 VARCHAR(12) UNIQUE NOT NULL,
    provider_user_id            UUID,
    provider_office_id          UUID,
    submission_type_code        VARCHAR(50),
    submission_date             TIMESTAMP,
    submission_period_start_date TIMESTAMP,
    submission_period_end_date   TIMESTAMP,
    schedule_id                 VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS claims (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ufn             VARCHAR(20)    NOT NULL,
    client          VARCHAR(50)    NOT NULL,
    category        VARCHAR(50)    NOT NULL,
    concluded       DATE           NOT NULL,
    fee_type        VARCHAR(50)    NOT NULL,
    claimed         DECIMAL(10, 2) NOT NULL,
    submission_id   UUID           NOT NULL,
    CONSTRAINT fk_submission FOREIGN KEY (submission_id) REFERENCES submissions(id)
);

CREATE SEQUENCE submission_friendly_id_seq START WITH 2;


