auth:
  mock:
    issuer: https://laa-claim-for-payment-mock-oidc-uat.cloud-platform.service.justice.gov.uk
    redirect-ssr: http://localhost:8080/login/oauth2/code/ssr
    logout-ssr: https://laa-claim-for-payment-frontend-uat.cloud-platform.service.justice.gov.uk