security:
  enabled: false 
logging.level:
  root: INFO
  org.springframework.security.oauth2.jwt: DEBUG
  org.springframework.security.oauth2.server.resource: DEBUG
  org.springframework.security.web.access.ExceptionTranslationFilter: DEBUG
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081
      client:
        provider:
          auth-server:
            issuer-uri: http://stub-oidc-server:8091    
civilclaims:
  api:
    base-url: http://localhost:8090
    #token: my-secret-token
    timeout: 30s    
          
