security:
  enabled: false   # feature-flag flip to true when the client is ready
spring:
  application:
    name: LAA Claim for Payment
  profiles:
    # Profile groups let you turn on multiple profiles with one name
    group:
      docker: "local"
      local-entra: "local_entra"
      uat: "uat"         
      staging: "staging" 
      prod: "prod"       
    default: local

# used by actuator info endpoint
info:
  app:
    name: LAA Civil CLaim for Payment Service
    description: Provides a REST API to Claim and Assess frontends.
    version: 1.0.0

management:
  # specify actuator endpoints to enable
  endpoints:
    web:
      exposure:
        include: health,info

  # show detailed health status
  endpoint:
    health:
      show-details: always

  info:
    env:
      enabled: true

civilclaims:
  api:
    base-url: https://laa-data-stewardship-payments-dev.apps.live.cloud-platform.service.justice.gov.uk/
    #token: my-secret-token
    timeout: 30s

logging.level.root: INFO