name: zap.yml
on:
  schedule:
    - cron: "0 0 * * *" # Daily at midnight
  workflow_call:
    secrets:
      PAT_TOKEN:
        required: true
      SENTRY_DSN:
        required: true
      AZURE_CLIENT_ID:
        required: true
      AZURE_CLIENT_SECRET:
        required: true
      AZURE_TENANT_ID:
        required: true
      SLACK_WEBHOOK_URL:
        required: true

permissions:
  contents: read
  packages: write

jobs:
  zap_scan:
    name: Scan the web application
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      SPRING_PROFILES_ACTIVE: local
      CLAIMS_API: http://localhost:8081
      PROVIDER_API: http://localhost:8081
      SENTRY_ENVIRONMENT: local
      REDIS_URL: redis://localhost:6379
      FEEDBACK_URL: /
      LAA_URL: /
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          ref: ${{ inputs.branch }}
      - name: Set up JDK 25
        uses: actions/setup-java@v5.2.0
        with:
          java-version: 25
          distribution: corretto
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5.0.0
      - name: Start app with local profile
        run: |
          echo "INFO: Running application..."
          ./gradlew build
          docker compose up -d &

          url="http://localhost:8080/actuator/health"
          retries=20

          for i in $(seq 1 $retries); do
            echo "INFO: Checking application health (attempt $i of $retries)..."
            if curl -sf "$url" | grep -q '"status":"UP"'; then
              echo "INFO: Application is healthy";
              exit 0;
            fi
            sleep 2
          done

          echo "ERROR: Application did not start"           
          exit 1
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.13.0 # https://github.com/zaproxy/action-full-scan
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'http://localhost:8080/v3/api-docs' # Exposes 'View' links for ZAP spider to discover
          rules_file_name: '.zap/rules.tsv'
          allow_issue_writing: false
          cmd_options: '-z "-config spider.maxDepth=10" -n zap.context' # https://www.zaproxy.org/docs/docker/full-scan/#usage
      - name: Capture app logs
        if: always()
        run: docker logs claim-for-payment-service > zap_output.log 2>&1
      - name: Upload logs
        uses: actions/upload-artifact@v6.0.0
        with:
          name: zap-scan-artifacts
          path: |
            report_html.html
            zap_output.log
          retention-days: 1
      - name: Notify Slack on failure
        if: failure()
        uses: slackapi/slack-github-action@v2.1.1
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: >
              :x: ZAP job failed!
              Download the zap_scan report. Use zap_output.log for help debugging if needed. The artifacts are available here:
              https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}